---

name: Build

on:
  - pull_request
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - flat-manager

    steps:
    - name: Clone
      uses: actions/checkout@v2

    - name: Build
      run: |
        cd ${{ matrix.image }}
        docker build -t ${{ matrix.image }}:latest .
