---

name: Build

on:
  - pull_request
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Clone
      uses: actions/checkout@v2

    - name: Build
      run: |
        docker build -t flat-manager-docker:latest .
        docker run --rm -i -v ./.hadolint.yaml:/root/.config/hadolint.yaml hadolint/hadolint < Dockerfile

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Clone
      uses: actions/checkout@v2

    - name: Lint
      run: |
        docker run --rm -i -v ./.hadolint.yaml:/root/.config/hadolint.yaml hadolint/hadolint < Dockerfile
