name: Publish
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 1 * *'
jobs:
  build:
    name: Build flat-manager-docker
    runs-on: ubuntu-latest

    steps:
    - name: Clone
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
        docker build -t elementary/flat-manager-:latest .
        docker push elementary/flat-manager-:latest
