---

name: Publish

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - name: Clone
      uses: actions/checkout@v2

    - name: Build
      run: |
        docker build -t elementary/flat-manager-docker:latest .

    - name: Publish
      run: |
        docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
        docker push elementary/flat-manager-docker:latest
