---

name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - flat-manager

    steps:
    - name: Clone
      uses: actions/checkout@v2

    - name: Build
      run: |
        cd ${{ matrix.image }}
        docker build -t elementary/${{ matrix.image }}:latest .

    - name: Publish
      run: |
        docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
        docker push elementary/${{ matrix.image }}:latest
